### ISSUE TITLE
THUCNews

### ISSUE THREAD

**Issue by hexiahui** [songyingxin/Bert-TextClassification#1]

**Comment by hexiahui** [comment]
输入提取码时显示提取码错误，能麻烦确认一下吗谢谢～

**Comment by songyingxin** [comment]
没有问题啊， 是THUCNews数据集吗？ 我这没有问题的，你再试试。

**Comment by hexiahui** [comment]
嗯好了 数据集没问题了～出了点小错误23333 补充问个问题，我在评测结果里看到了AUC值，这是只适用于二分类的评价指标，跑SST2时没有问题，但是CNEWS是多分类的，sklearn部分就报了'multiclass format is not supported’的错误，请问这个地方您是否有所设置？还是我漏了什么选项

**Comment by songyingxin** [comment]
已经修复了，在多标签时返回0.5， 不做考虑了已经。

**Comment by hexiahui** [comment]
好的 我重新下载一份测试下 谢谢～
| |
何夏辉
|
|
hxhecnu@126.com
|
签名由网易邮箱大师定制


On 05/29/2019 14:41，songyingxin<notifications@github.com> wrote：

已经修复了，在多标签时返回0.5， 不做考虑了已经。

**Comment by hexiahui** [comment]
好的 我重新下载一份测试下 谢谢～

**Comment by songyingxin** [comment]
不客气哦
