### ISSUE TITLE
Missing key(s) in state_dict: "classifier.weight", "classifier.bias".

### ISSUE THREAD

**Issue by km1994** [songyingxin/Bert-TextClassification#8]
File "D:\progrom\python\python\python3\lib\site-packages\torch\nn\modules\module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BertOrigin:
        Missing key(s) in state_dict: "classifier.weight", "classifier.bias".
        Unexpected key(s) in state_dict: "cls.predictions.bias", "cls.predictions.transform.dense.weight", "cls.predictions.transform.dense.bias", "cls.predictions.transform.LayerNorm.weight", "cls.predictions.transform.LayerNorm.bias", "cls.predictions.decoder.weight", "cls.seq_relationship.weight", "cls.seq_relationship.bias".

**Comment by hi-wangyan** [comment]
@km1994  Do you have solve the problem? I also miss the mistake

**Comment by PhoebusSi** [comment]
@km1994 Do you have solved the problem? I also miss the mistake
